export const mockSummaries = {
  'CALL-0001': {
    gist: 'Customer requested pricing and appointment booking for the AI receptionist.',
    outcome: 'Demo Scheduled',
    intent: 'Pricing Inquiry',
    sentiment: 'Positive',
    actionItems: ['Send pricing PDF', 'Confirm demo time', 'Prepare onboarding proposal'],
    keywords: ['Pricing', 'Demo', 'AI Receptionist', 'Appointment Booking'],
  },
  'CALL-0002': {
    gist: 'Prospect asked about enterprise packages and multi-agent routing.',
    outcome: 'Follow-up planned',
    intent: 'Enterprise Inquiry',
    sentiment: 'Neutral',
    actionItems: ['Share enterprise quote', 'Confirm seat count', 'Send ROI summary'],
    keywords: ['Enterprise', 'Routing', 'Support', 'Contracts'],
  },
  'CALL-0003': {
    gist: 'Customer needed help enabling recording and Google Drive export.',
    outcome: 'Setup instructions shared',
    intent: 'Technical Setup',
    sentiment: 'Positive',
    actionItems: ['Enable recording', 'Connect Google Drive', 'Verify transcript access'],
    keywords: ['Recording', 'Drive Export', 'Transcription', 'Setup'],
  },
  'CALL-0004': {
    gist: 'Caller experienced a dropped demo request and was missed by the queue.',
    outcome: 'Support ticket created',
    intent: 'Customer Support',
    sentiment: 'Neutral',
    actionItems: ['Reschedule demo', 'Review missed call workflow'],
    keywords: ['Missed Call', 'Demo', 'Support', 'Callback'],
  },
  'CALL-0005': {
    gist: 'Inbound user asked about outbound campaign billing and export capabilities.',
    outcome: 'Cost reporting confirmed',
    intent: 'Billing Inquiry',
    sentiment: 'Positive',
    actionItems: ['Share billing guide', 'Confirm campaign settings'],
    keywords: ['Billing', 'Outbound', 'Cost Reports', 'Campaigns'],
  },
  'CALL-0006': {
    gist: 'Outbound call failed due to destination carrier restrictions.',
    outcome: 'Route escalation opened',
    intent: 'Connection Issue',
    sentiment: 'Negative',
    actionItems: ['Retry on alternate route', 'Notify engineering', 'Confirm destination number'],
    keywords: ['Carrier', 'Failed Call', 'Outbound', 'Route'],
  },
  'CALL-0007': {
    gist: 'Prospect confirmed multi-language support and IVR routing for Spanish/English.' ,
    outcome: 'Language support validated',
    intent: 'Product Inquiry',
    sentiment: 'Positive',
    actionItems: ['Document language options', 'Share multi-language demo'],
    keywords: ['Spanish', 'English', 'IVR', 'Routing'],
  },
  'CALL-0008': {
    gist: 'Customer asked about live transcription and dashboard search features.',
    outcome: 'Feature details delivered',
    intent: 'Feature Inquiry',
    sentiment: 'Neutral',
    actionItems: ['Send demo screenshots', 'Highlight transcript search'],
    keywords: ['Transcription', 'Dashboard', 'Search', 'Live'],
  },
  'CALL-0009': {
    gist: 'Caller wanted AI summaries for team review and objection tracking.',
    outcome: 'Summary capabilities explained',
    intent: 'Analytics Inquiry',
    sentiment: 'Positive',
    actionItems: ['Schedule analytics walkthrough', 'Share summary examples'],
    keywords: ['Summaries', 'Sentiment', 'Coaching', 'Objections'],
  },
  'CALL-0010': {
    gist: 'Caller was disconnected before support could assist.',
    outcome: 'Follow-up committed',
    intent: 'Support',
    sentiment: 'Neutral',
    actionItems: ['Reopen ticket', 'Ensure callback before end of day'],
    keywords: ['Missed Support', 'Callback', 'Ticket'],
  },
  'CALL-0011': {
    gist: 'Customer asked about annual plan benefits and dedicated success support.',
    outcome: 'Enterprise terms shared',
    intent: 'Pricing Inquiry',
    sentiment: 'Positive',
    actionItems: ['Send annual plan summary', 'Confirm success manager availability'],
    keywords: ['Annual Plan', 'Discount', 'Support', 'Enterprise'],
  },
  'CALL-0012': {
    gist: 'Outbound call failed to a supplier number and was marked as a connection issue.',
    outcome: 'Route investigation started',
    intent: 'Failure Analysis',
    sentiment: 'Negative',
    actionItems: ['Investigate carrier route', 'Retry call later'],
    keywords: ['Failed Call', 'Dialer', 'Supplier', 'Routing'],
  },
  'CALL-0013': {
    gist: 'Prospect wants a new European sales line with unified dashboard control.',
    outcome: 'Provisioning plan ready',
    intent: 'Number Provisioning',
    sentiment: 'Positive',
    actionItems: ['Provision EU line', 'Replicate IVR flow'],
    keywords: ['EU Number', 'Dashboard', 'Provisioning', 'IVR'],
  },
  'CALL-0014': {
    gist: 'Caller reviewed AI receptionist pricing for a 10-seat team and holiday schedules.',
    outcome: 'Quote pending',
    intent: 'Pricing Inquiry',
    sentiment: 'Positive',
    actionItems: ['Prepare 10-seat quote', 'Document holiday rules'],
    keywords: ['AI Receptionist', 'Holidays', 'IVR', 'Pricing'],
  },
  'CALL-0015': {
    gist: 'Customer asked about personality settings and branded greetings for AI agents.',
    outcome: 'Persona feature explained',
    intent: 'Feature Inquiry',
    sentiment: 'Positive',
    actionItems: ['Share persona examples', 'Set up greeting flow'],
    keywords: ['Personality', 'Branded Greeting', 'AI Agent'],
  },
  'CALL-0016': {
    gist: 'Caller missed support contact and requested immediate follow-up.',
    outcome: 'Escalation created',
    intent: 'Support',
    sentiment: 'Neutral',
    actionItems: ['Assign follow-up', 'Confirm response time'],
    keywords: ['Support', 'Missed Call', 'Follow-up'],
  },
  'CALL-0017': {
    gist: 'Prospect inquired about multilingual support and language-specific analytics.',
    outcome: 'Language analytics confirmed',
    intent: 'Product Inquiry',
    sentiment: 'Positive',
    actionItems: ['Share multilingual overview', 'Show language performance charts'],
    keywords: ['Multilingual', 'Analytics', 'Support', 'French'],
  },
  'CALL-0018': {
    gist: 'Customer asked about product line routing and after-hours callback schedules.',
    outcome: 'Routing solution outlined',
    intent: 'Workflow Inquiry',
    sentiment: 'Positive',
    actionItems: ['Build after-hours flow', 'Configure callback alerts'],
    keywords: ['Routing', 'After Hours', 'Callbacks', 'Workflow'],
  },
  'CALL-0019': {
    gist: 'Outbound destination failed and a retry procedure was requested.',
    outcome: 'Retry scheduled',
    intent: 'Connection Issue',
    sentiment: 'Negative',
    actionItems: ['Retry destination', 'Review carrier route'],
    keywords: ['Retry', 'Failed Call', 'Carrier'],
  },
  'CALL-0020': {
    gist: 'Client needed schedule integration for Google and Outlook with no-show alerts.',
    outcome: 'Integration confirmed',
    intent: 'Scheduling Inquiry',
    sentiment: 'Positive',
    actionItems: ['Connect calendar accounts', 'Enable no-show alerts'],
    keywords: ['Calendar', 'Scheduling', 'No-show', 'Integration'],
  },
  'CALL-0021': {
    gist: 'Customer wanted AI analytics for objection tracking and team coaching.',
    outcome: 'Analytics walkthrough suggested',
    intent: 'Reporting Inquiry',
    sentiment: 'Positive',
    actionItems: ['Schedule analytics review', 'Prepare objection summary'],
    keywords: ['Analytics', 'Coaching', 'Objections', 'Team'],
  },
  'CALL-0022': {
    gist: 'Caller asked about average duration and sentiment trend reporting.',
    outcome: 'Reporting details shared',
    intent: 'Performance Inquiry',
    sentiment: 'Neutral',
    actionItems: ['Show sentiment dashboard', 'Highlight average duration metrics'],
    keywords: ['Sentiment', 'Duration', 'Reports', 'Trends'],
  },
  'CALL-0023': {
    gist: 'Missed incoming support call was logged for follow-up.',
    outcome: 'Support ticket reopened',
    intent: 'Support',
    sentiment: 'Neutral',
    actionItems: ['Reopen ticket', 'Prioritize callback'],
    keywords: ['Missed Call', 'Support', 'Callback'],
  },
  'CALL-0024': {
    gist: 'Customer requested a new EU number with consistent IVR across regions.',
    outcome: 'Provisioning started',
    intent: 'Number Setup',
    sentiment: 'Positive',
    actionItems: ['Provision EU number', 'Clone IVR flow'],
    keywords: ['EU', 'IVR', 'Provisioning', 'Numbers'],
  },
  'CALL-0025': {
    gist: 'Caller wanted per-rep tracking and automatic note capture for leads.',
    outcome: 'Feature usage confirmed',
    intent: 'Tracking Inquiry',
    sentiment: 'Positive',
    actionItems: ['Enable rep tracking', 'Review note capture options'],
    keywords: ['Rep Tracking', 'Notes', 'Lead Management'],
  },
  'CALL-0026': {
    gist: 'Prospect asked whether AI can answer FAQs and escalate complex issues.',
    outcome: 'Knowledge base workflow explained',
    intent: 'AI Capability Inquiry',
    sentiment: 'Positive',
    actionItems: ['Upload FAQ content', 'Test escalation path'],
    keywords: ['FAQ', 'Escalation', 'Knowledge Base'],
  },
  'CALL-0027': {
    gist: 'Caller reported an unconnected line and requested a retry.',
    outcome: 'Carrier escalation opened',
    intent: 'Connection Issue',
    sentiment: 'Neutral',
    actionItems: ['Retry route', 'Notify support team'],
    keywords: ['Unconnected', 'Carrier', 'Retry'],
  },
  'CALL-0028': {
    gist: 'Customer asked if the summary report can surface top questions asked this month.',
    outcome: 'Summary reporting confirmed',
    intent: 'Analytics Inquiry',
    sentiment: 'Positive',
    actionItems: ['Show top keyword report', 'Schedule analytics demo'],
    keywords: ['Top Questions', 'Summary', 'Keywords', 'Monthly'],
  },
  'CALL-0029': {
    gist: 'Outbound call failed and the destination route was flagged for troubleshooting.',
    outcome: 'Troubleshoot in progress',
    intent: 'Failure Analysis',
    sentiment: 'Negative',
    actionItems: ['Investigate route', 'Retry later'],
    keywords: ['Failed', 'Troubleshoot', 'Routing'],
  },
  'CALL-0030': {
    gist: 'Customer requested a smart triage flow to separate support and sales leads.',
    outcome: 'Demo requested',
    intent: 'Workflow Design',
    sentiment: 'Positive',
    actionItems: ['Build triage flow', 'Schedule product demo'],
    keywords: ['Triage', 'Support', 'Sales', 'Workflow'],
  },
};
