export const mockTranscripts = {
  'CALL-0001': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hello, thank you for calling KallUs AI Voice. My name is Maya, how can I help you today?' },
    { speaker: 'Customer', timestamp: '00:08', text: 'Hi Maya, I wanted to learn more about your receptionist pricing and whether it supports appointment booking.' },
    { speaker: 'Agent', timestamp: '00:18', text: 'Absolutely. We offer monthly and annual plans with built-in scheduling, calendar syncing, and automated reminders.' },
    { speaker: 'Customer', timestamp: '00:30', text: 'That sounds good. Do you also provide voicemail transcription and SMS follow-up?' },
    { speaker: 'Agent', timestamp: '00:42', text: 'Yes — every call can be transcribed automatically, and we can send follow-up notes to your team via SMS or email.' },
    { speaker: 'Customer', timestamp: '00:52', text: 'Great. Let’s schedule a demo for tomorrow afternoon.' },
    { speaker: 'Agent', timestamp: '00:58', text: 'Perfect, I’ve booked you for 2:00 PM and sent a calendar invite to your email. Anything else I can help with?' },
  ],
  'CALL-0002': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hey, this is Aaron from KallUs. I’m calling to follow up on your trial request.' },
    { speaker: 'Customer', timestamp: '00:10', text: 'Hi Aaron, yes, I’m interested in the AI receptionist but need to understand the enterprise plan details.' },
    { speaker: 'Agent', timestamp: '00:19', text: 'Our enterprise package includes unlimited minutes, advanced routing, and dedicated onboarding support.' },
    { speaker: 'Customer', timestamp: '00:29', text: 'Do you support multiple agents on a single phone number?' },
    { speaker: 'Agent', timestamp: '00:35', text: 'Absolutely. You can assign calls to any team member and use shared call notes in the dashboard.' },
    { speaker: 'Customer', timestamp: '00:44', text: 'Okay, I’ll review the quote and get back to you this afternoon.' },
  ],
  'CALL-0003': [
    { speaker: 'Agent', timestamp: '00:00', text: 'KallUs support, this is Jared. How can I support your team today?' },
    { speaker: 'Customer', timestamp: '00:06', text: 'Hello, I need help setting up call recording for our sales line.' },
    { speaker: 'Agent', timestamp: '00:12', text: 'I can walk you through that. Are you using one of our local or toll-free numbers?' },
    { speaker: 'Customer', timestamp: '00:18', text: 'We have a toll-free number, and we want the recordings exported to Google Drive.' },
    { speaker: 'Agent', timestamp: '00:28', text: 'Great, I’ll enable automatic recording and connect your Drive account from the integrations page.' },
    { speaker: 'Customer', timestamp: '00:36', text: 'Perfect. What about searchable transcripts for those recordings?' },
    { speaker: 'Agent', timestamp: '00:42', text: 'All calls will be transcribed and indexed, so you can search keywords across the whole history.' },
  ],
  'CALL-0004': [
    { speaker: 'Customer', timestamp: '00:00', text: 'Hi, I was calling about a demo but got dropped before anyone answered.' },
    { speaker: 'Agent', timestamp: '00:06', text: 'I’m sorry about that. We missed your call on the line and will follow up with a confirmation email.' },
  ],
  'CALL-0005': [
    { speaker: 'Agent', timestamp: '00:00', text: 'KallUs support, Maya speaking.' },
    { speaker: 'Customer', timestamp: '00:04', text: 'I’d like to understand how your billing works for outbound voice campaigns.' },
    { speaker: 'Agent', timestamp: '00:11', text: 'Outbound calls are priced per minute, and we provide detailed cost tracking per campaign.' },
    { speaker: 'Customer', timestamp: '00:19', text: 'Do you offer bulk exporting for call cost reports?' },
    { speaker: 'Agent', timestamp: '00:23', text: 'Yes, you can export full CSVs with cost, sentiment, and agent performance for every call.' },
    { speaker: 'Customer', timestamp: '00:30', text: 'Great, I’ll add that to our monthly review.' },
  ],
  'CALL-0006': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hi, it looks like your last outbound call could not connect. I’m here to help.' },
    { speaker: 'Customer', timestamp: '00:08', text: 'Thanks. The dialer kept failing on the client number.' },
    { speaker: 'Agent', timestamp: '00:12', text: 'I see a carrier blockage on that destination. I’ll pass it to engineering and suggest an alternate route.' },
    { speaker: 'Customer', timestamp: '00:19', text: 'Please do. We need that client contact to go through today.' },
  ],
  'CALL-0007': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Good morning, this is Nina from KallUs. Can I help answer questions about your account?' },
    { speaker: 'Customer', timestamp: '00:08', text: 'Yes, I want to know if your voice agents can handle Spanish and English seamlessly.' },
    { speaker: 'Agent', timestamp: '00:15', text: 'Yes, our AI detects language automatically and can respond in the same language when configured.' },
    { speaker: 'Customer', timestamp: '00:24', text: 'Do I need separate phone numbers for each language?' },
    { speaker: 'Agent', timestamp: '00:28', text: 'No, one number can serve multiple languages with our routing rules and AI language model.' },
  ],
  'CALL-0008': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hi, this is Aaron. I’m checking in about your demo setup.' },
    { speaker: 'Customer', timestamp: '00:06', text: 'I wanted to confirm the steps for enabling live call transcription.' },
    { speaker: 'Agent', timestamp: '00:11', text: 'Live transcription is on by default for every call and can be toggled per number.' },
    { speaker: 'Customer', timestamp: '00:17', text: 'Great. What does the transcript dashboard look like for managers?' },
    { speaker: 'Agent', timestamp: '00:22', text: 'They can search by keywords, filter by agent, and export summaries in one click.' },
  ],
  'CALL-0009': [
    { speaker: 'Agent', timestamp: '00:00', text: 'KallUs voice line, Maya speaking.' },
    { speaker: 'Customer', timestamp: '00:04', text: 'I’m interested in AI summaries for a weekly team review.' },
    { speaker: 'Agent', timestamp: '00:10', text: 'Our summaries highlight intent, sentiment, action items, and keywords automatically.' },
    { speaker: 'Customer', timestamp: '00:16', text: 'Can I use those summaries for coaching sessions?' },
    { speaker: 'Agent', timestamp: '00:19', text: 'Absolutely. They’re designed to let managers review calls faster and identify follow-ups.' },
  ],
  'CALL-0010': [
    { speaker: 'Customer', timestamp: '00:00', text: 'I called earlier about a support issue and got disconnected.' },
    { speaker: 'Agent', timestamp: '00:06', text: 'I’m sorry about that. I’ll reopen your ticket and make sure an agent reaches out before end of day.' },
  ],
  'CALL-0011': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hello, this is Maya from KallUs. What can I do for you today?' },
    { speaker: 'Customer', timestamp: '00:07', text: 'I need help reviewing the pricing for an annual subscription.' },
    { speaker: 'Agent', timestamp: '00:12', text: 'The annual plan comes with a 15% discount, priority support, and premium reporting.' },
    { speaker: 'Customer', timestamp: '00:19', text: 'Do you also include a dedicated success manager?' },
    { speaker: 'Agent', timestamp: '00:22', text: 'Yes, enterprise customers receive a success manager and onboarding services.' },
  ],
  'CALL-0012': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hi, I’m checking the failed call you just reported.' },
    { speaker: 'Customer', timestamp: '00:06', text: 'Yes, the outbound call to our supplier didn’t go through.' },
    { speaker: 'Agent', timestamp: '00:10', text: 'I’ve flagged the destination. We can retry it on a different route this afternoon.' },
  ],
  'CALL-0013': [
    { speaker: 'Agent', timestamp: '00:00', text: 'KallUs support, Aaron speaking.' },
    { speaker: 'Customer', timestamp: '00:05', text: 'I want to activate a second line for our European sales team.' },
    { speaker: 'Agent', timestamp: '00:12', text: 'We can provision a new local number in minutes and route it to your existing agents.' },
    { speaker: 'Customer', timestamp: '00:20', text: 'Can the same dashboard manage both numbers?' },
    { speaker: 'Agent', timestamp: '00:24', text: 'Yes, all lines appear in one unified dashboard with live reporting.' },
  ],
  'CALL-0014': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Good afternoon, this is Maya. How can I assist with your call setup?' },
    { speaker: 'Customer', timestamp: '00:06', text: 'I’m evaluating AI receptionist pricing for a team of 10.' },
    { speaker: 'Agent', timestamp: '00:13', text: 'The 10-seat bundle includes priority routing, call whisper, and reporting dashboards.' },
    { speaker: 'Customer', timestamp: '00:20', text: 'Does it support holiday schedules and custom IVR prompts?' },
    { speaker: 'Agent', timestamp: '00:25', text: 'Yes, you can customize IVR flows and holidays per number directly in the portal.' },
  ],
  'CALL-0015': [
    { speaker: 'Agent', timestamp: '00:00', text: 'KallUs line, Jared speaking.' },
    { speaker: 'Customer', timestamp: '00:06', text: 'I’ve got questions about the AI agent personality settings.' },
    { speaker: 'Agent', timestamp: '00:12', text: 'You can choose a formal or friendly voice persona and tune the responses in the dashboard.' },
    { speaker: 'Customer', timestamp: '00:18', text: 'Does it support branded greetings for callers?' },
    { speaker: 'Agent', timestamp: '00:22', text: 'Yes, we can record a custom welcome message and route calls based on the caller’s intent.' },
  ],
  'CALL-0016': [
    { speaker: 'Customer', timestamp: '00:00', text: 'I called to speak with support but didn’t reach anyone.' },
    { speaker: 'Agent', timestamp: '00:05', text: 'I’m sorry for the missed connection. I’ll make sure our agents follow up with you right away.' },
  ],
  'CALL-0017': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Bonjour, c’est Aaron de KallUs. Comment puis-je vous aider aujourd’hui?' },
    { speaker: 'Customer', timestamp: '00:08', text: 'Je souhaite savoir si l’agent vocal peut gérer plusieurs langues pour nos clients.' },
    { speaker: 'Agent', timestamp: '00:16', text: 'Oui, la plateforme détecte la langue et adapte les réponses automatiquement.' },
    { speaker: 'Customer', timestamp: '00:24', text: 'Parfait. Est-ce que je peux avoir un tableau de bord de performance pour chaque langue?' },
    { speaker: 'Agent', timestamp: '00:30', text: 'Absolument, chaque appel est étiqueté par langue et par sentiment.' },
  ],
  'CALL-0018': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hi Omar, this is Maya from KallUs. I can help with your voice agent setup.' },
    { speaker: 'Customer', timestamp: '00:06', text: 'I need to know if the system can route calls by product line.' },
    { speaker: 'Agent', timestamp: '00:13', text: 'Yes, you can route by caller intent, product interest, or availability rules.' },
    { speaker: 'Customer', timestamp: '00:20', text: 'Excellent. We need the calls routed to specific teams after hours.' },
    { speaker: 'Agent', timestamp: '00:26', text: 'We can create an after-hours flow with voicemail capture and callback scheduling.' },
  ],
  'CALL-0019': [
    { speaker: 'Agent', timestamp: '00:00', text: 'This call could not connect. I’m following up to schedule a retry or troubleshoot the destination.' },
    { speaker: 'Customer', timestamp: '00:07', text: 'Please retry the number after 30 minutes; it is the only way to reach the customer.' },
  ],
  'CALL-0020': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hi, this is Nina from KallUs. I’m confirming the details for your schedule integration.' },
    { speaker: 'Customer', timestamp: '00:06', text: 'I want call appointments to sync with Google Calendar and Outlook.' },
    { speaker: 'Agent', timestamp: '00:12', text: 'We support both. Once connected, booked demos and callbacks appear automatically.' },
    { speaker: 'Customer', timestamp: '00:18', text: 'Great, I also need alerts for no-shows.' },
    { speaker: 'Agent', timestamp: '00:22', text: 'We can add no-show flags and follow-up reminders for your team.' },
  ],
  'CALL-0021': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hi, this is Aaron. I’m calling to review how your team uses the conversation analytics.' },
    { speaker: 'Customer', timestamp: '00:08', text: 'I want to see if the AI summary can identify repeat objections automatically.' },
    { speaker: 'Agent', timestamp: '00:14', text: 'It can. We tag common objections and build a keyword heatmap for coaching.' },
    { speaker: 'Customer', timestamp: '00:21', text: 'That would be very helpful in our weekly standups.' },
  ],
  'CALL-0022': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Good afternoon, this is Maya. I’m following up on your account health review.' },
    { speaker: 'Customer', timestamp: '00:07', text: 'Yes, I wanted to understand the average call duration and sentiment trends.' },
    { speaker: 'Agent', timestamp: '00:13', text: 'You can view both in the reports dashboard with weekly charts and sentiment breakdowns.' },
    { speaker: 'Customer', timestamp: '00:19', text: 'Can the system flag negative calls automatically?' },
    { speaker: 'Agent', timestamp: '00:22', text: 'Yes, any negative sentiment call can be pushed to a coach queue for review.' },
  ],
  'CALL-0023': [
    { speaker: 'Customer', timestamp: '00:00', text: 'I called for support and the line rang out before anyone picked up.' },
    { speaker: 'Agent', timestamp: '00:05', text: 'We missed your call. I’ll make sure a specialist responds within the hour.' },
  ],
  'CALL-0024': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hi, this is Nina. I understand you need a new EU number for outbound demos.' },
    { speaker: 'Customer', timestamp: '00:08', text: 'Yes, and I’d like to keep the same IVR flow across both US and EU lines.' },
    { speaker: 'Agent', timestamp: '00:13', text: 'That’s possible. We can replicate your IVR flow and keep all data in one account.' },
    { speaker: 'Customer', timestamp: '00:18', text: 'Great, let’s proceed with the provisioning.' },
  ],
  'CALL-0025': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hello, this is Aaron from KallUs. How can I help today?' },
    { speaker: 'Customer', timestamp: '00:05', text: 'I’d like to track which sales rep spoke with each lead.' },
    { speaker: 'Agent', timestamp: '00:10', text: 'You can tag calls by agent and see a per-rep cost and conversion summary.' },
    { speaker: 'Customer', timestamp: '00:16', text: 'Do you also capture notes automatically during the call?' },
    { speaker: 'Agent', timestamp: '00:21', text: 'Yes, transcription notes are attached to every recording and stored in the timeline.' },
  ],
  'CALL-0026': [
    { speaker: 'Agent', timestamp: '00:00', text: 'This is Maya from KallUs. I’m calling about your outbound campaign setup.' },
    { speaker: 'Customer', timestamp: '00:07', text: 'I want to know if the agent can answer frequently asked questions automatically.' },
    { speaker: 'Agent', timestamp: '00:13', text: 'Yes, our AI can handle FAQs and escalate more complex questions to a human agent.' },
    { speaker: 'Customer', timestamp: '00:19', text: 'Perfect. How do I train it on our product catalog?' },
    { speaker: 'Agent', timestamp: '00:23', text: 'You can upload product details to the knowledge base and test responses in the simulator.' },
  ],
  'CALL-0027': [
    { speaker: 'Customer', timestamp: '00:00', text: 'I tried calling but the line never connected.' },
    { speaker: 'Agent', timestamp: '00:05', text: 'I’m sorry for the delay. I’ll ask our team to retry the call and escalate the route.' },
  ],
  'CALL-0028': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hi, this is Jared. I’m reviewing your voice analytics request.' },
    { speaker: 'Customer', timestamp: '00:06', text: 'Can I get a summary of the most asked questions this month?' },
    { speaker: 'Agent', timestamp: '00:12', text: 'Yes, the AI summary surfaces top keywords and repeated intents from your call history.' },
    { speaker: 'Customer', timestamp: '00:18', text: 'That would help our training team a lot.' },
  ],
  'CALL-0029': [
    { speaker: 'Agent', timestamp: '00:00', text: 'I’m following up on the call that failed to connect to your contact.' },
    { speaker: 'Customer', timestamp: '00:06', text: 'Please investigate the route and let me know if there is a carrier issue.' },
  ],
  'CALL-0030': [
    { speaker: 'Agent', timestamp: '00:00', text: 'Hello, this is Maya from KallUs. I can help you confirm your onboarding details.' },
    { speaker: 'Customer', timestamp: '00:07', text: 'I want a call flow that can triage support and sales leads automatically.' },
    { speaker: 'Agent', timestamp: '00:13', text: 'We can create a smart flow that asks two qualifying questions and routes accordingly.' },
    { speaker: 'Customer', timestamp: '00:20', text: 'Perfect, I’d like to see the demo before we finalize the workflow.' },
  ],
};
